[package]
name = "harvey"
version = "0.0.0"
authors = ["Morgan Phillips <winter2718@gmail.com>"]

[dependencies.toy-gc]

git = "https://github.com/jorendorff/rust-toy-gc"

[dependencies.readline]

git = "https://github.com/shaleh/rust-readline"
